# Setup
title:               Ankita Gupta
tagline:             ''
description:         ''
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Ankita Gupta
  url:               https://github.com/ankitagupta12
  email:             ankita@indydevs.org

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
